server:
  address: localhost
  port: 8080
  shutdown: graceful
loggin:
  level:
    root: true
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/flab?createDatabaseIfNotExist=true&&allowPublicKeyRetrieval=true&&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
    open-in-view: false  # TODO - open-in-view 의 의미가 무엇인지 확인하기. true 를 쓸지 false 를 쓸지 나름의 기준을 생각해보기
  flyway:
    user: root
    password: root
    schemas: flab
    url: jdbc:mysql://localhost:3306/flab?allowPublicKeyRetrieval=true&&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    enabled: true



