server:
  address: localhost
  port: 8080
  shutdown: graceful
loggin:
  level:
    root: true
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1Q2w3e4r@@
    url: jdbc:mysql://localhost:3306/jpa_practice?allowPublicKeyRetrieval=true&&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: jpa_practice
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true



